package com.example.connectfour.Board;

import java.util.Objects;

/**Class which represents a coordinate on the connect four grid.**/
public class Coordinate {
    private int width;
    private int height;


    /**Initialises the Coordinate with a width and height.**/
    public Coordinate(int width, int height){
        this.width = width;
        this.height = height;
    }

    /**Method which returns the coordinates position of width and height as a string.**/
    @Override
    public String toString(){
        return "Coordinate{" +
                "width = " + width +
                "; height = " + height +
                "}";
    }

    /**Method which returns width of Coordinate.**/
    public int getWidth() {
        return width;
    }

    /**Method which returns height of Coordinate.**/
    public int getHeight() {
        return height;
    }

    //FOLLOWING METHODS ARE GENERATED BY ANDROID STUDIO:
    /**Method which returns true if comparison is equal.**/
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Coordinate that = (Coordinate) o;
        return width == that.width &&
                height == that.height;
    }

    /**Method which returns Objects integer hashcode values.**/
    @Override
    public int hashCode() {
        return Objects.hash(width, height);
    }
}
